CC=nvcc
PROJ=smpv

CUDA_PATH=/usr/local/cuda

CFLAGS := -I$(CUDA_PATH)/samples/common/inc
CFLAGS  += -I$(CALI_DIR)/include

LDFLAGS := -L$(CALI_DIR)/lib64 -lcaliper -lcaliper-common

srcFiles = \
  spmv.cu \
  spmv_support.cu 
  
all: $(PROJ) 

$(PROJ): $(srcFiles) 
	$(CC) $(CFLAGS) $(srcFiles) -o $@ $(LDFLAGS)

clean:
	rm -rf $(PROJ) 
